/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sales;

import Main.StartWindow;
import Purchase.ProductPurchase;
import Purchase.PurchasePaid;
import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sakib
 */
public class ProductSales extends javax.swing.JFrame {

    /**
     * Creates new form ProductSales
     */
    public ProductSales() {
        initComponents();
        connect();
        loadWindow();
        comboBox();
    }
Connection con;
PreparedStatement pst=null;
ResultSet rs=null,rs2=null,rs3=null,rs4=null,rs5=null,rs6=null,rs7=null,rs8=null,rs9=null,rs10=null,rs11=null;
int oldAmounts=0,stockIdQty=0,stockQty=0;
 String totalQtyid="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtVoucharNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        productNCombo = new javax.swing.JComboBox<>();
        txtDeliveryPlace = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPurchasePrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        employeNCombo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSellsPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtLtr_Kg = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        oldAmount = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        todayAmount = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        finalAmount = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtPaid = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        due = new javax.swing.JLabel();
        rbbkash = new javax.swing.JRadioButton();
        rbcash = new javax.swing.JRadioButton();
        rbcheck = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        totalAmount = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        customerNCombo = new javax.swing.JComboBox<>();
        productIdCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TotalQuantity = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        TotalIdQuantity = new javax.swing.JTextField();
        txtPacket = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtId = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("ComboBox.selectionForeground"));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(102, 255, 102));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel2.setText("*Product Sales : ");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 220, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Date", "Product Id", "Product Name", "Purchase Price", "Sales Price", "Quantity", "Total price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 250, 1250, 190);

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1140, 200, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Purchase price :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 180, 180, 30);

        txtVoucharNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVoucharNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVoucharNoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtVoucharNoMousePressed(evt);
            }
        });
        txtVoucharNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVoucharNoActionPerformed(evt);
            }
        });
        txtVoucharNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVoucharNoKeyPressed(evt);
            }
        });
        jPanel1.add(txtVoucharNo);
        txtVoucharNo.setBounds(10, 90, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Employe Name :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(400, 60, 150, 30);

        productNCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item" }));
        productNCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productNComboMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productNComboMouseEntered(evt);
            }
        });
        productNCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNComboActionPerformed(evt);
            }
        });
        jPanel1.add(productNCombo);
        productNCombo.setBounds(10, 150, 180, 30);

        txtDeliveryPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeliveryPlaceActionPerformed(evt);
            }
        });
        jPanel1.add(txtDeliveryPlace);
        txtDeliveryPlace.setBounds(560, 90, 220, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Delivery place :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(560, 60, 220, 30);

        txtPurchasePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPurchasePriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtPurchasePrice);
        txtPurchasePrice.setBounds(10, 210, 180, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Product name :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 120, 180, 30);

        employeNCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item" }));
        employeNCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeNComboActionPerformed(evt);
            }
        });
        jPanel1.add(employeNCombo);
        employeNCombo.setBounds(400, 90, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Vouchar no. :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 60, 180, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Sells price :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(200, 180, 180, 30);

        txtSellsPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSellsPriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtSellsPrice);
        txtSellsPrice.setBounds(200, 210, 180, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Liter / kg  :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(870, 200, 100, 30);

        txtLtr_Kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLtr_KgActionPerformed(evt);
            }
        });
        txtLtr_Kg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLtr_KgKeyPressed(evt);
            }
        });
        jPanel1.add(txtLtr_Kg);
        txtLtr_Kg.setBounds(970, 200, 120, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Total price :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(560, 180, 220, 30);

        txtTotalPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTotalPriceMouseClicked(evt);
            }
        });
        txtTotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalPrice);
        txtTotalPrice.setBounds(560, 210, 220, 30);

        oldAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        oldAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oldAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(oldAmount);
        oldAmount.setBounds(360, 550, 160, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Old Amount :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(360, 520, 160, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Today Amount :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 460, 160, 30);

        todayAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        todayAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        todayAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(todayAmount);
        todayAmount.setBounds(10, 490, 160, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Total Amount :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(190, 520, 160, 30);

        finalAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        finalAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        finalAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(finalAmount);
        finalAmount.setBounds(530, 550, 160, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Discount :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(190, 460, 160, 30);

        txtDiscount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDiscount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountActionPerformed(evt);
            }
        });
        txtDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiscountKeyPressed(evt);
            }
        });
        jPanel1.add(txtDiscount);
        txtDiscount.setBounds(190, 490, 160, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Paid :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(700, 460, 160, 30);

        txtPaid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPaid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaidActionPerformed(evt);
            }
        });
        txtPaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPaidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaidKeyReleased(evt);
            }
        });
        jPanel1.add(txtPaid);
        txtPaid.setBounds(700, 490, 160, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Due :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(700, 520, 160, 30);

        due.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        due.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        due.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(due);
        due.setBounds(700, 550, 160, 30);

        buttonGroup1.add(rbbkash);
        rbbkash.setText("Bkash");
        rbbkash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbkashActionPerformed(evt);
            }
        });
        jPanel1.add(rbbkash);
        rbbkash.setBounds(890, 550, 70, 30);

        buttonGroup1.add(rbcash);
        rbcash.setText("Cash");
        rbcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbcashActionPerformed(evt);
            }
        });
        jPanel1.add(rbcash);
        rbcash.setBounds(890, 510, 70, 30);

        buttonGroup1.add(rbcheck);
        rbcheck.setText("Check");
        rbcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbcheckActionPerformed(evt);
            }
        });
        jPanel1.add(rbcheck);
        rbcheck.setBounds(890, 470, 70, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(990, 510, 80, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Final amount :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(530, 520, 160, 30);

        totalAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(totalAmount);
        totalAmount.setBounds(190, 550, 160, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Customer Name :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(200, 60, 180, 30);

        customerNCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item" }));
        customerNCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNComboActionPerformed(evt);
            }
        });
        jPanel1.add(customerNCombo);
        customerNCombo.setBounds(200, 90, 180, 30);

        productIdCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item" }));
        productIdCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productIdComboMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productIdComboMouseEntered(evt);
            }
        });
        productIdCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productIdComboActionPerformed(evt);
            }
        });
        jPanel1.add(productIdCombo);
        productIdCombo.setBounds(200, 150, 180, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Product ID :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 120, 180, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Total quantity :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(400, 120, 150, 30);

        TotalQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalQuantityActionPerformed(evt);
            }
        });
        jPanel1.add(TotalQuantity);
        TotalQuantity.setBounds(400, 150, 150, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Total quantity ID wise :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(560, 120, 220, 30);

        TotalIdQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalIdQuantityActionPerformed(evt);
            }
        });
        jPanel1.add(TotalIdQuantity);
        TotalIdQuantity.setBounds(560, 150, 220, 30);

        txtPacket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacketActionPerformed(evt);
            }
        });
        txtPacket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPacketKeyPressed(evt);
            }
        });
        jPanel1.add(txtPacket);
        txtPacket.setBounds(970, 150, 120, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Quantity/Packet :");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(830, 150, 140, 30);

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantityKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });
        jPanel1.add(txtQuantity);
        txtQuantity.setBounds(400, 210, 150, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Quantity (Ltr/kg) :");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(400, 180, 150, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Report");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(1360, 440, 130, 50);

        txtId.setBackground(new java.awt.Color(153, 255, 153));
        txtId.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtId);
        txtId.setBounds(970, 110, 120, 30);

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(1180, 100, 80, 30);

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1180, 150, 80, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1290, 610);

        setSize(new java.awt.Dimension(1306, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void connect(){ 
        try {
            con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/chemical_company", "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(ProductSales.class.getName()).log(Level.SEVERE, null, ex);
        }
}
public void loadWindow(){
     String sid="0";
        try {
            pst=con.prepareStatement("select *from product_sales");
            rs=pst.executeQuery();
        while(rs.next()){
         sid=rs.getString(1);
        }
        int cid=Integer.parseInt(sid);
        cid=cid+1;
        sid=Integer.toString(cid);
        txtId.setText("Id : "+sid);
        } catch (SQLException ex) {
            Logger.getLogger(ProductSales.class.getName()).log(Level.SEVERE, null, ex);
        }
}
public void comboBox(){
        try {
            pst=con.prepareStatement("SELECT name FROM customer_information");
            rs=pst.executeQuery();
             while(rs.next()){
         customerNCombo.addItem(rs.getString(1));
        }
              pst=con.prepareStatement("SELECT product_name FROM product_purchase GROUP BY product_name");
            rs2=pst.executeQuery();
             while(rs2.next()){
         productNCombo.addItem(rs2.getString(1));
        }
              pst=con.prepareStatement("SELECT name FROM employe");
            rs3=pst.executeQuery();
             while(rs3.next()){
         employeNCombo.addItem(rs3.getString(1));
        }
            
        } catch (SQLException ex) {
            Logger.getLogger(ProductSales.class.getName()).log(Level.SEVERE, null, ex);
        }
}
public void loadTable(){
        //dateBox();
        if(txtVoucharNo.getText().isEmpty()==false){
        try {
         DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
            dt.setRowCount(0);
            String svnumber="";
            svnumber=txtVoucharNo.getText();
            int vnumber=Integer.parseInt(svnumber);
            pst=con.prepareStatement("select *from product_sales where vouchar_no=?");
            pst.setInt(1,vnumber);
            rs4=pst.executeQuery();
        while(rs4.next()){
         dt.addRow(new Object[]{rs4.getString(1),rs4.getString(2),rs4.getString(3),rs4.getString(4)
                                ,rs4.getString(5),rs4.getString(6),rs4.getString(7),rs4.getString(8)});
        }
      // clear();
        } catch (SQLException ex) {
            Logger.getLogger(ProductSales.class.getName()).log(Level.SEVERE, null, ex);
        }}
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //selected
        DefaultTableModel dt = (DefaultTableModel)jTable1.getModel();
        String id = dt.getValueAt(jTable1.getSelectedRow(),0).toString();
        String date = dt.getValueAt(jTable1.getSelectedRow(),1).toString();
        String pname = dt.getValueAt(jTable1.getSelectedRow(),2).toString();
        String purprice = dt.getValueAt(jTable1.getSelectedRow(),3).toString();
        String selprice= dt.getValueAt(jTable1.getSelectedRow(),4).toString();
        String quantity= dt.getValueAt(jTable1.getSelectedRow(),5).toString();
        String totprice= dt.getValueAt(jTable1.getSelectedRow(),6).toString();

     //   dateBox.setText(date);
        txtId.setText(id);
        productNCombo.setSelectedItem(pname);
        txtPurchasePrice.setText(purprice);
        txtSellsPrice.setText(selprice);
        txtLtr_Kg.setText(quantity);
        txtTotalPrice.setText(totprice);

    }//GEN-LAST:event_jTable1MouseClicked
public void add(){
        String voucharN=txtVoucharNo.getText();
        String customerN =customerNCombo.getSelectedItem().toString();
        String employeN =employeNCombo.getSelectedItem().toString();
        String delivaryP=txtDeliveryPlace.getText();
        String productN =productNCombo.getSelectedItem().toString();
        String productId =productIdCombo.getSelectedItem().toString();
       
        String totalQuantity=TotalQuantity.getText();
        String totalQuantityId=TotalIdQuantity.getText();        
        String purchaseP=txtPurchasePrice.getText();
        String salesP=txtSellsPrice.getText();
        String quantity=txtQuantity.getText();
        String totalPrice=txtTotalPrice.getText();
        String packet=txtPacket.getText();
        String ltrKg=txtLtr_Kg.getText();
        long millis=System.currentTimeMillis();  
        java.sql.Date date=new java.sql.Date(millis);  
         if(voucharN.isEmpty()== true ||delivaryP.isEmpty()==true||purchaseP.isEmpty()==true||
             salesP.isEmpty()== true ||quantity.isEmpty()==true||totalPrice.isEmpty()==true){
            JOptionPane.showMessageDialog(this,"Please enter all records.");
        }
         else if(customerNCombo.getSelectedIndex()==0 || productNCombo.getSelectedIndex()==0|| employeNCombo.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"Please select the items.");             
         } 
        else{ 
            try {  
        int voucharNi=Integer.parseInt(voucharN);
        int productIdi=Integer.parseInt(productId);
        int purchasePi=Integer.parseInt(purchaseP);        
        int salesPi=Integer.parseInt(salesP);
        int quantityi=Integer.parseInt(quantity);        
        int totalPricei=Integer.parseInt(totalPrice);  
        int packeti=Integer.parseInt(packet);  
                pst=con.prepareStatement("insert into product_sales (date,product_id,product_name,purchase_price,sales_price,quantity,total_price,vouchar_no,customer_name,employe_name,delivery_place,quantity_pack,litr_kg) values(?,?,?,?,?,?,?,?,?,?,?,?,?)");
                pst.setDate(1,date);
                pst.setInt(2,productIdi);
                pst.setString(3,productN);
                pst.setInt(4,purchasePi);
                pst.setInt(5,salesPi);
                pst.setInt(6,quantityi);
                pst.setInt(7,totalPricei);
                pst.setInt(8,voucharNi);
                pst.setString(9,customerN);
                pst.setString(10,employeN);
                pst.setString(11,delivaryP);
                pst.setInt(12,packeti);
                pst.setString(13,ltrKg);                
                pst.executeUpdate(); 
                JOptionPane.showMessageDialog(this,"Data add success !!!!!");
                loadTable();
                loadWindow();
                 calculate();  
//                clear();
            } catch (SQLException ex) {
                Logger.getLogger(ProductSales.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        }}
public void calculate(){
        try {
            int vn=Integer.parseInt( txtVoucharNo.getText());
            pst=con.prepareStatement("SELECT SUM(total_price) FROM `product_sales` WHERE `vouchar_no`=? GROUP BY `vouchar_no`");
            pst.setInt(1,vn);
            rs=pst.executeQuery();
            pst=con.prepareStatement("SELECT  SUM(total_price) FROM `product_sales` WHERE (`customer_name`=? AND `vouchar_no`<>?)GROUP BY `customer_name`");
            pst.setString(1,customerNCombo.getSelectedItem().toString());
            pst.setString(2,txtVoucharNo.getText());
            rs2=pst.executeQuery();
            pst=con.prepareStatement("SELECT SUM(`paid`) FROM `product_sales_collection` WHERE `customer_name`=? GROUP BY `customer_name`");
            pst.setString(1,customerNCombo.getSelectedItem().toString());
            rs3=pst.executeQuery();
             int paidtotal=0;
             int totalPur=0;
            while(rs.next()){
                todayAmount.setText(rs.getString(1));
            }
            while(rs2.next()){
                 totalPur=Integer.parseInt(rs2.getString(1));}
            while(rs3.next()){
             paidtotal=Integer.parseInt(rs3.getString(1));
             // paid=paid+paidtotal;
            }
            oldAmounts=totalPur-paidtotal;
            String totalPurs=Integer.toString(oldAmounts);
            oldAmount.setText(totalPurs);}
           catch (SQLException ex) {
            Logger.getLogger(ProductSales.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        add();
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtVoucharNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVoucharNoActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_txtVoucharNoActionPerformed

    private void productNComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productNComboMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_productNComboMouseClicked

    private void productNComboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productNComboMouseEntered

    }//GEN-LAST:event_productNComboMouseEntered
public void calculateQty(){
        try {
            String result1,result2,result3,result4;
            int purQty=0,selQty=0;
            pst=con.prepareStatement("SELECT  SUM(`quantity`) FROM `product_purchase` WHERE `product_name`=?");
            pst.setString(1,productNCombo.getSelectedItem().toString());
            rs5=pst.executeQuery();
            pst=con.prepareStatement("SELECT  SUM(`quantity`) FROM `product_sales` WHERE `product_name`=?");
            pst.setString(1,productNCombo.getSelectedItem().toString());
            rs6=pst.executeQuery();
            String purQtys=null,selQtys=null,rslt3=null,rslt4=null;
            while(rs5.next()){
                purQtys=rs5.getString(1);
            }
            if(purQtys!=null){
                purQty=Integer.parseInt(purQtys); 
            }
            while(rs6.next()){
             selQtys=rs6.getString(1);
           }
            if(selQtys!=null){
                selQty=Integer.parseInt(selQtys); 
            }
            stockQty=purQty-selQty;
            TotalQuantity.setText(stockQty+"");       
        } catch (SQLException ex) {
            Logger.getLogger(ProductSales.class.getName()).log(Level.SEVERE, null, ex);
        }
}
public void pprice(){
        try {
            if(productIdCombo.getSelectedItem()!=null){
            String pids;
            pids=productIdCombo.getSelectedItem().toString();
            int pid=Integer.parseInt(pids);
            
            pst=con.prepareStatement("SELECT `purchase_price`,`sales_price` FROM `product_purchase` WHERE `id`=?");
            pst.setInt(1,pid);
            rs7=pst.executeQuery();
            while(rs7.next()){
                txtPurchasePrice.setText(rs7.getString(1));
                txtSellsPrice.setText(rs7.getString(2));
            }}  
        } catch (SQLException ex) {
            Logger.getLogger(ProductSales.class.getName()).log(Level.SEVERE, null, ex);
        }
}
public void addItem(){
                try {
                productIdCombo.removeAllItems();
                TotalQuantity.setText("");
                TotalIdQuantity.setText("");
                txtPurchasePrice.setText("");
                txtSellsPrice.setText("");
                if(productNCombo.getSelectedIndex()>0){                        
                pst=con.prepareStatement("SELECT id FROM product_purchase WHERE product_name=?");
                pst.setString(1,productNCombo.getSelectedItem().toString());
                rs9=pst.executeQuery();
                while(rs9.next()){
                    productIdCombo.addItem(rs9.getString(1));  }
                   }
                } catch (SQLException ex) {
                    Logger.getLogger(ProductSales.class.getName()).log(Level.SEVERE, null, ex);
                }
}
    private void productNComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNComboActionPerformed
             
        addItem();
        if(productNCombo.getSelectedIndex()>0){
          calculateQty();  
        }     
        
    }//GEN-LAST:event_productNComboActionPerformed
    private void txtDeliveryPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeliveryPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeliveryPlaceActionPerformed

    private void txtPurchasePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPurchasePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPurchasePriceActionPerformed

    private void employeNComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeNComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeNComboActionPerformed

    private void txtSellsPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSellsPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSellsPriceActionPerformed

    private void txtLtr_KgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLtr_KgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLtr_KgActionPerformed

    private void txtLtr_KgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLtr_KgKeyPressed
     
    }//GEN-LAST:event_txtLtr_KgKeyPressed
public void totalPrice(){
    int pp,q;
    pp=Integer.parseInt(txtPurchasePrice.getText());
    q=Integer.parseInt(txtQuantity.getText());
    int total=pp*q;
    txtTotalPrice.setText(Integer.toString(total));
}
    private void txtTotalPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTotalPriceMouseClicked
        // TODO add your handling code here:
       // totalPrice();
    }//GEN-LAST:event_txtTotalPriceMouseClicked

    private void txtTotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPriceActionPerformed

    private void txtDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscountActionPerformed

    private void txtDiscountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscountKeyPressed
        // Enter key
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            Amount();
        }

    }//GEN-LAST:event_txtDiscountKeyPressed

    private void txtPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaidActionPerformed

    private void txtPaidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaidKeyPressed
        // EnterPaid
         Amount();
        if (evt.getKeyCode()==KeyEvent.VK_ENTER && txtPaid.getText().isEmpty()==false){
           // calculate();
           paidCalculation();

        }
    }//GEN-LAST:event_txtPaidKeyPressed
public void paidCalculation(){
            int total=0,paid=0;
            total=Integer.parseInt(finalAmount.getText());
            paid=Integer.parseInt(txtPaid.getText());
            int finalAm=0;
            finalAm=total-paid;
            if(paid<=total){
            due.setText(finalAm+"");
            }
           
}
    private void txtPaidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaidKeyReleased
        // TODO add your handling code here:
        if( txtPaid.getText().isEmpty()==false){
             paidCalculation();
        }
        else{
            due.setText("");
        }
  
    }//GEN-LAST:event_txtPaidKeyReleased

    private void rbbkashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbkashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbbkashActionPerformed

    private void rbcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbcashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbcashActionPerformed

    private void rbcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbcheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbcheckActionPerformed
public void addAmount(){
        long millis=System.currentTimeMillis();  
        java.sql.Date date=new java.sql.Date(millis); 
        String voucharN=txtVoucharNo.getText();
        String events="";
        if(rbcash.isSelected()){
            events="Cash";
        }
        if(rbcheck.isSelected()){
            events="Check";
        }
        if(rbbkash.isSelected()){
            events="bKash";
        }
        String amounts=todayAmount.getText();
        String discounts=txtDiscount.getText();
        String totals=totalAmount.getText();
        String finalAmounts=oldAmount.getText();
        String paids=txtPaid.getText();
        String dues=due.getText();
        String customern =customerNCombo.getSelectedItem().toString();
         if(voucharN.isEmpty()== true ||events.isEmpty()==true||
            finalAmounts.isEmpty()==true||paids.isEmpty()==true){
            JOptionPane.showMessageDialog(this,"Please enter all records.");
        }
         else if(customerNCombo.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"Please select the items.");             
         } 
        else{ 
            try {
        int voucharni=Integer.parseInt(voucharN);
        int amounti=Integer.parseInt(amounts);        
        int discounti=Integer.parseInt(discounts);;        
        int totali=Integer.parseInt(totals);        
        int finalAmounti=Integer.parseInt(finalAmounts);  
        int paidi=Integer.parseInt(paids);  
        int duei=Integer.parseInt(dues);  
                pst=con.prepareStatement("insert into product_sales_collection(date,vouchar_number,event,amount,discount,total,final_amount,paid,due,customer_name) values(?,?,?,?,?,?,?,?,?,?)");
                pst.setDate(1,date);
                pst.setInt(2,voucharni);
                pst.setString(3,events);
                pst.setInt(4,amounti);
                pst.setInt(5,discounti);
                pst.setInt(6,totali);
                pst.setInt(7,finalAmounti);
                pst.setInt(8,paidi);
                pst.setInt(9,duei);
                pst.setString(10,customern);
                pst.executeUpdate(); 
                JOptionPane.showMessageDialog(this,"Data add success !!!!!");
                 new pSalesBillf().setVisible(true);
         this.dispose();
         //       clear();
       // showTable();
            } catch (SQLException ex) {
                Logger.getLogger(ProductSales.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        addAmount();
        refresh();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      refresh();
       // refresh();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void customerNComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNComboActionPerformed
        // TODO add your handling code here:
        if(!txtVoucharNo.getText().isEmpty()){
              calculate();   
        }  
        
    }//GEN-LAST:event_customerNComboActionPerformed

    private void productIdComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productIdComboMouseClicked
        // click
         
    }//GEN-LAST:event_productIdComboMouseClicked

    private void productIdComboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productIdComboMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_productIdComboMouseEntered
public void qtyId(){
        try {
            if(productIdCombo.getSelectedItem()!=null && productNCombo.getSelectedItem()!=null){
            String purIdQtys=null,selIdQtys=null;
            int purIdQty=0,selIdQty=0;
            String proname=productNCombo.getSelectedItem().toString();
            String proid=productIdCombo.getSelectedItem().toString();
            ResultSet purRes=null,selRes=null;    
            pst=con.prepareStatement("SELECT  SUM(`quantity`) FROM `product_purchase` WHERE `product_name`=? AND `id`=?");
            pst.setString(1,proname);
            pst.setString(2,proid);
            purRes=pst.executeQuery();
            pst=con.prepareStatement("SELECT  SUM(`quantity`) FROM `product_sales` WHERE `product_name`=? AND `product_id`=?");
            pst.setString(1,proname);
            pst.setString(2,proid);
            selRes=pst.executeQuery();
            while(purRes.next()){
                purIdQtys=purRes.getString(1);
            }
            if(purIdQtys!=null){
                purIdQty=Integer.parseInt(purIdQtys); 
            }
            while(selRes.next()){
                selIdQtys=selRes.getString(1);
            }
            if(selIdQtys!=null){
                selIdQty=Integer.parseInt(selIdQtys); 
            }
            stockIdQty=purIdQty-selIdQty;
           TotalIdQuantity.setText(stockIdQty+"");}
        } catch (SQLException ex) {
            Logger.getLogger(ProductSales.class.getName()).log(Level.SEVERE, null, ex);
        }
}

    private void productIdComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productIdComboActionPerformed
        // TODO add your handling code here:
        if(productNCombo.getSelectedIndex()>0){
           qtyId();
           pprice();

        }
            // TotalQuantityId.setText(totalQtyid);
              
    }//GEN-LAST:event_productIdComboActionPerformed

    private void TotalQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalQuantityActionPerformed

    private void TotalIdQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalIdQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalIdQuantityActionPerformed

    private void txtPacketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacketActionPerformed

    private void txtPacketKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPacketKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacketKeyPressed
public void Amount(){
           int todayAmounti=Integer.parseInt(todayAmount.getText());
           int discount =Integer.parseInt(txtDiscount.getText());
           int total=todayAmounti-discount;
            String totals=Integer.toString(total);
            totalAmount.setText(totals);
            int finalTotal=total+oldAmounts;
            String ftotals=Integer.toString(finalTotal);
            finalAmount.setText(ftotals);
}
public void refresh(){
    loadWindow();
    txtVoucharNo.setText("");
    txtDeliveryPlace.setText("");
    txtSellsPrice.setText("");
    txtPurchasePrice.setText("");
    txtQuantity.setText("");
    txtTotalPrice.setText("");
    productNCombo.setSelectedIndex(0);
    customerNCombo.setSelectedIndex(0);
    txtPaid.setText("");
    due.setText("");
    buttonGroup1.clearSelection();
    totalAmount.setText("");
    finalAmount.setText("");
    txtDiscount.setText("");
    todayAmount.setText("");
    oldAmount.setText("");
    DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
    dt.setRowCount(0);
}
    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // Enter key
      
        
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void txtQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyPressed
      if (evt.getKeyCode()==KeyEvent.VK_ENTER && txtQuantity.getText().isEmpty()==false ){
         Totalcalculation();
    }           // calculate();     
    }//GEN-LAST:event_txtQuantityKeyPressed
    public void Totalcalculation(){
         int qty=Integer.parseInt(txtQuantity.getText());
            int sellp=Integer.parseInt(txtSellsPrice.getText());
            sellp=qty*sellp;
            String total=Integer.toString(sellp);
            txtTotalPrice.setText(total);
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      new pSalesBillf().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new StartWindow().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
        // TODO add your handling code here:
         if (txtQuantity.getText().isEmpty()==false ){
         Totalcalculation();
    } 
    }//GEN-LAST:event_txtQuantityKeyReleased

    private void txtVoucharNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVoucharNoMouseClicked
        // TODO add your handling code here:
       

    }//GEN-LAST:event_txtVoucharNoMouseClicked

    private void txtVoucharNoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVoucharNoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVoucharNoMousePressed

    private void txtVoucharNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVoucharNoKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtVoucharNoKeyPressed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductSales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TotalIdQuantity;
    private javax.swing.JTextField TotalQuantity;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> customerNCombo;
    private javax.swing.JLabel due;
    private javax.swing.JComboBox<String> employeNCombo;
    private javax.swing.JLabel finalAmount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel oldAmount;
    private javax.swing.JComboBox<String> productIdCombo;
    private javax.swing.JComboBox<String> productNCombo;
    private javax.swing.JRadioButton rbbkash;
    private javax.swing.JRadioButton rbcash;
    private javax.swing.JRadioButton rbcheck;
    private javax.swing.JLabel todayAmount;
    private javax.swing.JLabel totalAmount;
    private javax.swing.JTextField txtDeliveryPlace;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JLabel txtId;
    private javax.swing.JTextField txtLtr_Kg;
    private javax.swing.JTextField txtPacket;
    private javax.swing.JTextField txtPaid;
    private javax.swing.JTextField txtPurchasePrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSellsPrice;
    private javax.swing.JTextField txtTotalPrice;
    private javax.swing.JTextField txtVoucharNo;
    // End of variables declaration//GEN-END:variables
}
