/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sales;

import Main.StartWindow;
import Purchase.PurchasePaid;
import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sakib
 */
public class ProductSalesCollection extends javax.swing.JFrame {
Connection con;    
PreparedStatement pst=null;
ResultSet rs=null,rs2=null,rs3=null; int oldAmounts=0;
    /**
     * Creates new form ProductSalesCollection
     */
    public ProductSalesCollection() {
        initComponents();
        connect();    
        comboBox();  
    }
//ResultSet rs,rs2=null,rs3=null; int oldAmounts=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        date = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        customerNCombo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        oldAmount = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtPaid = new javax.swing.JTextField();
        rbbkash = new javax.swing.JRadioButton();
        rbcash = new javax.swing.JRadioButton();
        rbcheck = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        due = new javax.swing.JTextField();
        txtVoucharNo = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBox.highlight"));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel2.setText("*Product Sells Collection : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 300, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Bill number", "Event", "Amount", "Discount", "Total", "Final amount", "Paid", "Due"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 1230, 220);
        jPanel1.add(date);
        date.setBounds(900, 10, 220, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Customer Name :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 50, 120, 30);

        customerNCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item" }));
        customerNCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerNComboMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customerNComboMouseEntered(evt);
            }
        });
        customerNCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNComboActionPerformed(evt);
            }
        });
        jPanel1.add(customerNCombo);
        customerNCombo.setBounds(140, 50, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Vouchar no. :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(320, 20, 100, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Old due :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 330, 180, 20);

        oldAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldAmountActionPerformed(evt);
            }
        });
        jPanel1.add(oldAmount);
        oldAmount.setBounds(20, 360, 180, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Paid :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(220, 330, 170, 20);

        txtPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaidActionPerformed(evt);
            }
        });
        txtPaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPaidKeyPressed(evt);
            }
        });
        jPanel1.add(txtPaid);
        txtPaid.setBounds(220, 360, 170, 30);

        buttonGroup1.add(rbbkash);
        rbbkash.setText("Bkash");
        rbbkash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbkashActionPerformed(evt);
            }
        });
        jPanel1.add(rbbkash);
        rbbkash.setBounds(750, 40, 120, 40);

        buttonGroup1.add(rbcash);
        rbcash.setText("Cash");
        rbcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbcashActionPerformed(evt);
            }
        });
        jPanel1.add(rbcash);
        rbcash.setBounds(490, 40, 120, 40);

        buttonGroup1.add(rbcheck);
        rbcheck.setText("Check");
        rbcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbcheckActionPerformed(evt);
            }
        });
        jPanel1.add(rbcheck);
        rbcheck.setBounds(620, 40, 120, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(650, 350, 130, 40);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Due :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(420, 330, 170, 20);

        due.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dueActionPerformed(evt);
            }
        });
        due.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dueKeyPressed(evt);
            }
        });
        jPanel1.add(due);
        due.setBounds(420, 360, 170, 30);

        txtVoucharNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVoucharNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtVoucharNo);
        txtVoucharNo.setBounds(310, 50, 160, 30);

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(1150, 50, 90, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1263, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void connect(){ 
        try {
            con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/chemical_company", "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(ProductSalesCollection.class.getName()).log(Level.SEVERE, null, ex);
        }
            }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void customerNComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerNComboMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_customerNComboMouseClicked

    private void customerNComboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerNComboMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_customerNComboMouseEntered
    public void comboBox(){
        try {
            pst=con.prepareStatement("SELECT `name` FROM `customer_information`");
            rs3=pst.executeQuery();
             while(rs3.next()){
         customerNCombo.addItem(rs3.getString(1));
        }
        } catch (SQLException ex) {
            Logger.getLogger(ProductSalesCollection.class.getName()).log(Level.SEVERE, null, ex);
        }

}
public void calculate(){
        try {
            pst=con.prepareStatement("SELECT  SUM(`total_price`) FROM `product_sales` WHERE `customer_name`=? GROUP BY `customer_name`");
            pst.setString(1,customerNCombo.getSelectedItem().toString());
            rs=pst.executeQuery();
            pst=con.prepareStatement("SELECT SUM(`paid`) FROM `product_sales_collection` WHERE `customer_name`=? GROUP BY `customer_name`");
            pst.setString(1,customerNCombo.getSelectedItem().toString());
            rs2=pst.executeQuery();
             int paid=0;
             int totalPur=0;
            while(rs.next()){
                 totalPur=Integer.parseInt(rs.getString(1));}
            while(rs2.next()){
                 paid =Integer.parseInt(rs2.getString(1));
            }
            oldAmounts=totalPur-paid;
            String totalPurs=Integer.toString(oldAmounts);
            oldAmount.setText(totalPurs);
            }
           catch (SQLException ex) {
            Logger.getLogger(ProductSalesCollection.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        }
    private void customerNComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNComboActionPerformed
        // TODO add your handling code here:
        select();
    }//GEN-LAST:event_customerNComboActionPerformed
public void addAmount(){
        long millis=System.currentTimeMillis();  
        java.sql.Date date=new java.sql.Date(millis); 
        String voucharN=txtVoucharNo.getText();
        String events="";
        if(rbcash.isSelected()){
            events="Cash";
        }
        if(rbcheck.isSelected()){
            events="Check";
        }
        if(rbbkash.isSelected()){
            events="bKash";
        }
        String amounts="0";
        String discounts="0";
        String totals="0";
        String finalAmounts=oldAmount.getText();
        String paids=txtPaid.getText();
        String dues=due.getText();
        String customern =customerNCombo.getSelectedItem().toString();
         if(voucharN.isEmpty()== true ||events.isEmpty()==true||
            finalAmounts.isEmpty()==true||paids.isEmpty()==true){
            JOptionPane.showMessageDialog(this,"Please enter all records.");
        }
         else if(customerNCombo.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"Please select the items.");             
         } 
        else{ 
            try {
        int voucharni=Integer.parseInt(voucharN);
        int amounti=0;        
        int discounti=0;        
        int totali=0;        
        int finalAmounti=Integer.parseInt(finalAmounts);  
        int paidi=Integer.parseInt(paids);  
        int duei=Integer.parseInt(dues);  
                pst=con.prepareStatement("INSERT INTO `product_sales_collection`(DATE,vouchar_number,EVENT,amount,discount,total,final_amount,paid,due,customer_name) VALUES(?,?,?,?,?,?,?,?,?,?)");
                pst.setDate(1,date);
                pst.setInt(2,voucharni);
                pst.setString(3,events);
                pst.setInt(4,amounti);
                pst.setInt(5,discounti);
                pst.setInt(6,totali);
                pst.setInt(7,finalAmounti);
                pst.setInt(8,paidi);
                pst.setInt(9,duei);
                pst.setString(10,customern);
                pst.executeUpdate(); 
                JOptionPane.showMessageDialog(this,"Data add success !!!!!");
                clear();
        calculate();
        showTable();
            } catch (SQLException ex) {
                Logger.getLogger(ProductSalesCollection.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        }
    }
public void clear(){
    txtVoucharNo.setText("");
    txtPaid.setText("");
    due.setText("");
    buttonGroup1.clearSelection();
}
public void showTable(){
        try {
            DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
            dt.setRowCount(0);
            String scustomer=customerNCombo.getSelectedItem().toString();
            pst=con.prepareStatement("SELECT *FROM `product_sales_collection` WHERE `customer_name`=?");
            pst.setString(1,scustomer);
            rs=pst.executeQuery();
            while(rs.next()){
                dt.addRow(new Object[]{rs.getString(2),rs.getString(3),rs.getString(4)
                        ,rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(ProductSalesCollection.class.getName()).log(Level.SEVERE, null, ex);
        }
}
public void select(){
      if(customerNCombo.getSelectedIndex()>=1){
             showTable();        
             calculate();   
         }
      else{
           DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
            dt.setRowCount(0);
             clear();
             oldAmount.setText("");
             
      }
}
    private void oldAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldAmountActionPerformed

    private void txtPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaidActionPerformed

    private void txtPaidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaidKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            int total=Integer.parseInt(oldAmount.getText());
            int paid=Integer.parseInt(txtPaid.getText());
            total=total-paid;
            String dues=Integer.toString(total);
            due.setText(dues);
        }
    }//GEN-LAST:event_txtPaidKeyPressed

    private void rbbkashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbkashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbbkashActionPerformed

    private void rbcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbcashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbcashActionPerformed

    private void rbcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbcheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbcheckActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addAmount();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void dueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dueActionPerformed

    private void dueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dueKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_dueKeyPressed

    private void txtVoucharNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVoucharNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVoucharNoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new StartWindow().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductSalesCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductSalesCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductSalesCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductSalesCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductSalesCollection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> customerNCombo;
    private javax.swing.JLabel date;
    private javax.swing.JTextField due;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField oldAmount;
    private javax.swing.JRadioButton rbbkash;
    private javax.swing.JRadioButton rbcash;
    private javax.swing.JRadioButton rbcheck;
    private javax.swing.JTextField txtPaid;
    private javax.swing.JTextField txtVoucharNo;
    // End of variables declaration//GEN-END:variables
}
