/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Purchase;

import Information_add.Supplier_information;
import Main.StartWindow;
import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sakib
 */
public class ProductPurchase extends javax.swing.JFrame {

    /**
     * Creates new form ProductPurchase
     */
    public ProductPurchase() {
        initComponents();
        connect();
        comboBox();
        loadWindow();
    }
Connection con;
PreparedStatement pst=null;
ResultSet rs=null,rs2=null,rs3=null;
int oldAmounts=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        dateBox = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtVoucharNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        productNCombo = new javax.swing.JComboBox<>();
        txtDeliveryPlace = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPurchasePrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        companyNCombo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSellsPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        oldAmount = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        todayAmount = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        finalAmount = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtPaid = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        due = new javax.swing.JLabel();
        rbbkash = new javax.swing.JRadioButton();
        rbcash = new javax.swing.JRadioButton();
        rbcheck = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        totalAmount = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Date", "Product Name", "Purchase Price", "Sales Price", "Quantity", "Total price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 200, 1240, 250);
        jPanel1.add(dateBox);
        dateBox.setBounds(880, 50, 220, 30);

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(980, 160, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Id : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(460, 70, 120, 30);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId);
        txtId.setBounds(460, 100, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Purchase price :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(260, 130, 180, 30);

        txtVoucharNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVoucharNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtVoucharNo);
        txtVoucharNo.setBounds(260, 100, 160, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Company Name :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 70, 210, 30);

        productNCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item" }));
        productNCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productNComboMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productNComboMouseEntered(evt);
            }
        });
        productNCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNComboActionPerformed(evt);
            }
        });
        jPanel1.add(productNCombo);
        productNCombo.setBounds(10, 160, 210, 30);

        txtDeliveryPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeliveryPlaceActionPerformed(evt);
            }
        });
        jPanel1.add(txtDeliveryPlace);
        txtDeliveryPlace.setBounds(610, 100, 180, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Delivery place :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(610, 70, 180, 30);

        txtPurchasePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPurchasePriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtPurchasePrice);
        txtPurchasePrice.setBounds(260, 160, 160, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Product name :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 130, 210, 30);

        companyNCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item" }));
        companyNCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyNComboActionPerformed(evt);
            }
        });
        jPanel1.add(companyNCombo);
        companyNCombo.setBounds(10, 100, 210, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Vouchar no. :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(260, 70, 160, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Sells price :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(460, 130, 120, 30);

        txtSellsPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSellsPriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtSellsPrice);
        txtSellsPrice.setBounds(460, 160, 120, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Quantity (Ltr/kg) :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(610, 130, 180, 30);

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantityKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });
        jPanel1.add(txtQuantity);
        txtQuantity.setBounds(610, 160, 180, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Total price :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(810, 130, 140, 30);

        txtTotalPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTotalPriceMouseClicked(evt);
            }
        });
        txtTotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalPrice);
        txtTotalPrice.setBounds(810, 160, 140, 30);

        oldAmount.setBackground(new java.awt.Color(255, 153, 153));
        oldAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        oldAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oldAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(oldAmount);
        oldAmount.setBounds(400, 550, 180, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Old Amount :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(400, 520, 180, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Today Amount :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 450, 180, 40);

        todayAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        todayAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        todayAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(todayAmount);
        todayAmount.setBounds(10, 490, 180, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Total Amount :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(200, 520, 180, 30);

        finalAmount.setBackground(new java.awt.Color(0, 0, 204));
        finalAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        finalAmount.setForeground(new java.awt.Color(255, 51, 0));
        finalAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        finalAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(finalAmount);
        finalAmount.setBounds(600, 550, 180, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Discount :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(200, 460, 180, 30);

        txtDiscount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDiscount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountActionPerformed(evt);
            }
        });
        txtDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiscountKeyPressed(evt);
            }
        });
        jPanel1.add(txtDiscount);
        txtDiscount.setBounds(200, 490, 180, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Paid :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(790, 460, 180, 30);

        txtPaid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPaid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaidActionPerformed(evt);
            }
        });
        txtPaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPaidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaidKeyReleased(evt);
            }
        });
        jPanel1.add(txtPaid);
        txtPaid.setBounds(790, 490, 180, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Due :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(790, 520, 180, 30);

        due.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        due.setForeground(new java.awt.Color(153, 0, 204));
        due.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        due.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(due);
        due.setBounds(790, 550, 180, 30);

        buttonGroup1.add(rbbkash);
        rbbkash.setText("bKash");
        rbbkash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbkashActionPerformed(evt);
            }
        });
        jPanel1.add(rbbkash);
        rbbkash.setBounds(1000, 560, 120, 30);

        buttonGroup1.add(rbcash);
        rbcash.setText("Cash");
        rbcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbcashActionPerformed(evt);
            }
        });
        jPanel1.add(rbcash);
        rbcash.setBounds(1000, 460, 120, 30);

        buttonGroup1.add(rbcheck);
        rbcheck.setText("Check");
        rbcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbcheckActionPerformed(evt);
            }
        });
        jPanel1.add(rbcheck);
        rbcheck.setBounds(1000, 510, 120, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Ok");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1150, 510, 70, 30);

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1140, 90, 90, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Final amount :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(600, 520, 180, 30);

        totalAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(totalAmount);
        totalAmount.setBounds(200, 550, 180, 30);

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(1160, 40, 70, 30);

        jLabel5.setBackground(new java.awt.Color(102, 255, 102));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel5.setText("*Product Purchase : ");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 20, 230, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1260, 650);

        setSize(new java.awt.Dimension(1276, 690));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void connect(){ 
            try {
                con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/chemical_company", "root", "");
            } catch (SQLException ex) {
                Logger.getLogger(ProductPurchase.class.getName()).log(Level.SEVERE, null, ex);
            }
}
    public void dateBox(){
        DateTimeFormatter cdt = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        String cdate=cdt.format(now);
        dateBox.setText(cdate);
    }
    private void txtTotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPriceActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void txtSellsPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSellsPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSellsPriceActionPerformed

    private void txtPurchasePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPurchasePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPurchasePriceActionPerformed

    private void txtDeliveryPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeliveryPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeliveryPlaceActionPerformed

    private void txtVoucharNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVoucharNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVoucharNoActionPerformed
public void loadWindow(){
     String sid="0";
        try {
            pst=con.prepareStatement("select *from product_purchase");
            rs=pst.executeQuery();
        while(rs.next()){
         sid=rs.getString(1);
        }
        int cid=Integer.parseInt(sid);
        cid=cid+1;
        sid=Integer.toString(cid);
        txtId.setText(sid);
        companyNCombo.requestFocus();
        } catch (SQLException ex) {
            Logger.getLogger(ProductPurchase.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed
public void loadTable(){
        //dateBox();
        if(txtVoucharNo.getText().isEmpty()==false){
        try {
         DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
         dt.setRowCount(0);
            String svnumber="";
            svnumber=txtVoucharNo.getText();
            int vnumber=Integer.parseInt(svnumber);
            pst=con.prepareStatement("select *from product_purchase where vouchar_number=?");
            pst.setInt(1,vnumber);
            rs=pst.executeQuery();
        while(rs.next()){
         dt.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)
                                ,rs.getString(5),rs.getString(6),rs.getString(7)});
        }
        //  clear();
        } catch (SQLException ex) {
            Logger.getLogger(ProductPurchase.class.getName()).log(Level.SEVERE, null, ex);
        }}
    }
public void refresh(){
    loadWindow();
    txtVoucharNo.setText("");
    txtDeliveryPlace.setText("");
    txtSellsPrice.setText("");
    txtPurchasePrice.setText("");
    txtQuantity.setText("");
    txtTotalPrice.setText("");
    productNCombo.setSelectedIndex(0);
    companyNCombo.setSelectedIndex(0);
    txtPaid.setText("");
    due.setText("");
    buttonGroup1.clearSelection();
    totalAmount.setText("");
    finalAmount.setText("");
    txtDiscount.setText("");
    todayAmount.setText("");
    oldAmount.setText("");
    DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
    dt.setRowCount(0);
}
public void comboBox(){
        try {
            pst=con.prepareStatement("SELECT company_name FROM supplier_information");
            rs=pst.executeQuery();
             while(rs.next()){
         companyNCombo.addItem(rs.getString(1));
        }
              pst=con.prepareStatement("SELECT pName FROM product_information");
            rs=pst.executeQuery();
             while(rs.next()){
         productNCombo.addItem(rs.getString(1));
        }
            
        } catch (SQLException ex) {
            Logger.getLogger(ProductPurchase.class.getName()).log(Level.SEVERE, null, ex);
        }

}
public void pprice(){
      if(productNCombo.getSelectedIndex()>0){        
        try {
            String proName= productNCombo.getSelectedItem().toString();
            pst=con.prepareStatement("SELECT purchasePrice,sellsPrice FROM product_information WHERE pName=?");
            pst.setString(1,proName);
            rs=pst.executeQuery();
           
            while(rs.next()){
                txtPurchasePrice.setText(rs.getString(1));
                txtSellsPrice.setText(rs.getString(2));
            }    
        } catch (SQLException ex) {
            Logger.getLogger(ProductPurchase.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
      else{
           txtPurchasePrice.setText("");
                txtSellsPrice.setText("");
      }
}
public void add(){
        String voucharN=txtVoucharNo.getText();
        String delivaryPl=txtDeliveryPlace.getText();
        String salesP=txtSellsPrice.getText();
        String purchaseP=txtPurchasePrice.getText();
        String quantity=txtQuantity.getText();
        String total=txtTotalPrice.getText();
        String companyn =companyNCombo.getSelectedItem().toString();
        String productn =productNCombo.getSelectedItem().toString();
        long millis=System.currentTimeMillis();  
        java.sql.Date date=new java.sql.Date(millis);  
         if(voucharN.isEmpty()== true ||delivaryPl.isEmpty()==true||salesP.isEmpty()==true||purchaseP.isEmpty()==true||total.isEmpty()==true){
            JOptionPane.showMessageDialog(this,"Please enter all records.");
        }
         else if(companyNCombo.getSelectedIndex()==0 || productNCombo.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"Please select the items.");             
         } 
        else{ 
            try {
        int voucharn=Integer.parseInt(voucharN);
        int salesp=Integer.parseInt(salesP);
        int purchasep=Integer.parseInt(purchaseP);        
        int quantitys=Integer.parseInt(quantity);        
        int totals=Integer.parseInt(total);  
                pst=con.prepareStatement("insert into product_purchase (date,product_name,purchase_price,sales_price,quantity,total_price,company_name,vouchar_number,delivery_place) values(?,?,?,?,?,?,?,?,?)");
                pst.setDate(1,date);
                pst.setString(2,productn);
                pst.setInt(3,purchasep);
                pst.setInt(4,salesp);
                pst.setInt(5,quantitys);
                pst.setInt(6,totals);
                pst.setString(7,companyn);
                pst.setInt(8,voucharn);
                pst.setString(9,delivaryPl);
                
                pst.executeUpdate(); 
                JOptionPane.showMessageDialog(this,"Data add success !!!!!");
//                clear();
            } catch (SQLException ex) {
                Logger.getLogger(Supplier_information.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        }}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       add();
       loadTable();
       todayAmounts();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //selected
        DefaultTableModel dt = (DefaultTableModel)jTable1.getModel();
        String id = dt.getValueAt(jTable1.getSelectedRow(),0).toString();
        String date = dt.getValueAt(jTable1.getSelectedRow(),1).toString();
        String pname = dt.getValueAt(jTable1.getSelectedRow(),2).toString();
        String purprice = dt.getValueAt(jTable1.getSelectedRow(),3).toString();
        String selprice= dt.getValueAt(jTable1.getSelectedRow(),4).toString();
        String quantity= dt.getValueAt(jTable1.getSelectedRow(),5).toString();
        String totprice= dt.getValueAt(jTable1.getSelectedRow(),6).toString();
        
        dateBox.setText(date);
        txtId.setText(id);
        productNCombo.setSelectedItem(pname);
        txtPurchasePrice.setText(purprice);
        txtSellsPrice.setText(selprice);
        txtQuantity.setText(quantity);
        txtTotalPrice.setText(totprice);
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void productNComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productNComboMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_productNComboMouseClicked

    private void productNComboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productNComboMouseEntered
     
        
    }//GEN-LAST:event_productNComboMouseEntered

    private void productNComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNComboActionPerformed
          // clicked
        pprice();
        txtQuantity.setText("");
        txtTotalPrice.setText("");
    }//GEN-LAST:event_productNComboActionPerformed

    private void txtDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscountActionPerformed

    private void txtPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaidActionPerformed

    private void rbbkashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbkashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbbkashActionPerformed

    private void rbcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbcashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbcashActionPerformed

    private void rbcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbcheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbcheckActionPerformed
public void totalPrice(){
    int pp,q;
    pp=Integer.parseInt(txtPurchasePrice.getText());
    q=Integer.parseInt(txtQuantity.getText());
    int total=pp*q;
    txtTotalPrice.setText(Integer.toString(total));
}
    private void txtQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyPressed
        //enter quantity
        if (evt.getKeyCode()==KeyEvent.VK_ENTER && txtQuantity.getText().isEmpty()==false ){
        totalPrice();
    }
    }//GEN-LAST:event_txtQuantityKeyPressed

    private void txtTotalPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTotalPriceMouseClicked
        // TODO add your handling code here:
        totalPrice();
    }//GEN-LAST:event_txtTotalPriceMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Refresh
        refresh();
    }//GEN-LAST:event_jButton3ActionPerformed
public void todayAmounts(){
        try {
            int vn=Integer.parseInt( txtVoucharNo.getText());
            pst=con.prepareStatement("SELECT SUM(total_price) FROM `product_purchase` WHERE `vouchar_number`=?\n" +
"GROUP BY vouchar_number");
            pst.setInt(1,vn);
            rs=pst.executeQuery();
            while(rs.next()){
                todayAmount.setText(rs.getString(1));
            }
            }
           catch (SQLException ex) {
            Logger.getLogger(ProductPurchase.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }
public void oldAmountM(){
        try {
            pst=con.prepareStatement("SELECT  SUM(total_price) FROM `product_purchase` WHERE (`company_name`=?\n" +
                    "AND `vouchar_number`<> ?) GROUP BY `company_name`");
            pst.setString(1,companyNCombo.getSelectedItem().toString());
            pst.setString(2,txtVoucharNo.getText());
            rs2=pst.executeQuery();
            pst=con.prepareStatement("SELECT SUM(`paid`) FROM `purchase_due_paid` WHERE `company_name`=?\n" +
                    "GROUP BY `company_name`");
            pst.setString(1,companyNCombo.getSelectedItem().toString());
            rs3=pst.executeQuery();
            int paid=0;
            int totalPur=0;
            while(rs2.next()){
                totalPur=Integer.parseInt(rs2.getString(1));}
            while(rs3.next()){
                int paidtotal=Integer.parseInt(rs3.getString(1));
                paid=paid+paidtotal;
            }
            oldAmounts=totalPur-paid;
            String totalPurs=Integer.toString(oldAmounts);
            oldAmount.setText(totalPurs);
        } catch (SQLException ex) {
            Logger.getLogger(ProductPurchase.class.getName()).log(Level.SEVERE, null, ex);
        }
}
public void addAmount(){
        long millis=System.currentTimeMillis();  
        java.sql.Date date=new java.sql.Date(millis); 
        String voucharN=txtVoucharNo.getText();
        String events="";
        if(rbcash.isSelected()){
            events="Cash";
        }
        if(rbcheck.isSelected()){
            events="Check";
        }
        if(rbbkash.isSelected()){
            events="bKash";
        }
        String amounts=todayAmount.getText();
        String discounts=txtDiscount.getText();
        String totals=totalAmount.getText();
        String finalAmounts=finalAmount.getText();
        String paids=txtPaid.getText();
        String dues=due.getText();
        String companyn =companyNCombo.getSelectedItem().toString();
         if(voucharN.isEmpty()== true ||events.isEmpty()==true||amounts.isEmpty()==true||discounts.isEmpty()==true||totals.isEmpty()==true
                 ||finalAmounts.isEmpty()==true||paids.isEmpty()==true||dues.isEmpty()==true){
            JOptionPane.showMessageDialog(this,"Please enter all records.");
        }
         else if(companyNCombo.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"Please select the items.");             
         } 
        else{ 
            try {
        int voucharni=Integer.parseInt(voucharN);
        int amounti=Integer.parseInt(amounts);        
        int discounti=Integer.parseInt(discounts);        
        int totali=Integer.parseInt(totals);        
        int finalAmounti=Integer.parseInt(finalAmounts);  
        int paidi=Integer.parseInt(paids);  
        int duei=Integer.parseInt(dues);  
                pst=con.prepareStatement("insert into purchase_due_paid(date,vouchar_number,event,amount,discount,total,final_amount,paid,due,company_name) values(?,?,?,?,?,?,?,?,?,?)");
                pst.setDate(1,date);
                pst.setInt(2,voucharni);
                pst.setString(3,events);
                pst.setInt(4,amounti);
                pst.setInt(5,discounti);
                pst.setInt(6,totali);
                pst.setInt(7,finalAmounti);
                pst.setInt(8,paidi);
                pst.setInt(9,duei);
                pst.setString(10,companyn);
                pst.executeUpdate(); 
                JOptionPane.showMessageDialog(this,"Data add success !!!!!");
            } catch (SQLException ex) {
                Logger.getLogger(ProductPurchase.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        }
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        addAmount();
        refresh();
    }//GEN-LAST:event_jButton1ActionPerformed
public void Amount(){
            int purchase_total=Integer.parseInt(todayAmount.getText());
            int discount =Integer.parseInt(txtDiscount.getText());
            int total=purchase_total-discount;
           // String totals=Integer.toString(total);
            totalAmount.setText(total+"");
            int finalTotal=total+oldAmounts;
           // String ftotals=Integer.toString(finalTotal);
            finalAmount.setText(finalTotal+"");
}
    private void txtDiscountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscountKeyPressed
        // Enter key
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
          Amount();
          txtPaid.requestFocus();
    }    
    }//GEN-LAST:event_txtDiscountKeyPressed

    private void txtPaidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaidKeyPressed
        // EnterPaid
          if (evt.getKeyCode()==KeyEvent.VK_ENTER){
         int total=Integer.parseInt(finalAmount.getText());
         int paid=Integer.parseInt(txtPaid.getText());
         total=total-paid;
         String dues=Integer.toString(total);
         due.setText(dues);
         rbcash.setSelected(true);
    }
    }//GEN-LAST:event_txtPaidKeyPressed

    private void companyNComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyNComboActionPerformed
        // TODO add your handling code here:
        oldAmountM();
    }//GEN-LAST:event_companyNComboActionPerformed

    private void txtPaidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaidKeyReleased

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
        // TODO add your handling code here:
         if( txtQuantity.getText().isEmpty()==false ){
              totalPrice();
         }
       
    }//GEN-LAST:event_txtQuantityKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new StartWindow().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductPurchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> companyNCombo;
    private javax.swing.JLabel dateBox;
    private javax.swing.JLabel due;
    private javax.swing.JLabel finalAmount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel oldAmount;
    private javax.swing.JComboBox<String> productNCombo;
    private javax.swing.JRadioButton rbbkash;
    private javax.swing.JRadioButton rbcash;
    private javax.swing.JRadioButton rbcheck;
    private javax.swing.JLabel todayAmount;
    private javax.swing.JLabel totalAmount;
    private javax.swing.JTextField txtDeliveryPlace;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPaid;
    private javax.swing.JTextField txtPurchasePrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSellsPrice;
    private javax.swing.JTextField txtTotalPrice;
    private javax.swing.JTextField txtVoucharNo;
    // End of variables declaration//GEN-END:variables
}
