/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Data_entry;
import Main.StartWindow;
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sakib
 */
public class Con_eng_commission extends javax.swing.JFrame {

    /**
     * Creates new form Con_eng_commission
     */
    public Con_eng_commission() {
        initComponents();
        connect();
        comboBox();
        loadWindow();
    }
Connection con;
PreparedStatement pst=null;
ResultSet rs=null,rs2=null,rs3=null,rs4=null,rs5=null,rs6=null,rs7=null,rs8=null,rs9=null,rs10=null,rs11=null;
int oldAmounts=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        date = new javax.swing.JLabel();
        txtMobileNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        designationCombo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        conEngrNCombo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtProfession = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDetails = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Designation", "Name", "Mobile", "Profession", "Category", "Details", "Amount"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 190, 1240, 280);
        jPanel1.add(date);
        date.setBounds(900, 10, 220, 30);

        txtMobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtMobileNo);
        txtMobileNo.setBounds(350, 90, 200, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Designation :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 60, 90, 30);

        designationCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item" }));
        designationCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                designationComboMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                designationComboMouseEntered(evt);
            }
        });
        designationCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designationComboActionPerformed(evt);
            }
        });
        jPanel1.add(designationCombo);
        designationCombo.setBounds(20, 90, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Mobile no. :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(420, 60, 70, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(830, 150, 90, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Name :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 60, 60, 30);

        conEngrNCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item" }));
        conEngrNCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conEngrNComboMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                conEngrNComboMouseEntered(evt);
            }
        });
        conEngrNCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conEngrNComboActionPerformed(evt);
            }
        });
        jPanel1.add(conEngrNCombo);
        conEngrNCombo.setBounds(190, 90, 140, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Profession :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(640, 60, 90, 30);

        txtProfession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessionActionPerformed(evt);
            }
        });
        jPanel1.add(txtProfession);
        txtProfession.setBounds(580, 90, 180, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Category :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 120, 70, 30);

        txtCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoryActionPerformed(evt);
            }
        });
        jPanel1.add(txtCategory);
        txtCategory.setBounds(20, 150, 150, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Details :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(340, 120, 50, 30);

        txtDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDetailsActionPerformed(evt);
            }
        });
        jPanel1.add(txtDetails);
        txtDetails.setBounds(190, 150, 360, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Amount :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(640, 120, 70, 30);

        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        jPanel1.add(txtAmount);
        txtAmount.setBounds(580, 150, 180, 30);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId);
        txtId.setBounds(860, 90, 60, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Id : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(820, 90, 40, 30);

        jLabel13.setBackground(new java.awt.Color(102, 255, 102));
        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel13.setText(" *Con/Eng commission add  : ");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 10, 330, 50);

        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(1120, 90, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1260, 600);

        setSize(new java.awt.Dimension(1277, 642));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void connect(){ 
        try {
            con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/chemical_company", "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(Con_eng_commission.class.getName()).log(Level.SEVERE, null, ex);
        }
}
public void comboBox(){
        try {
            pst=con.prepareStatement("SELECT `designation` FROM `contructor_engineer` GROUP BY `designation`");
            rs=pst.executeQuery();
             while(rs.next()){
         designationCombo.addItem(rs.getString(1));
        }            
        } catch (SQLException ex) {
            Logger.getLogger(Con_eng_commission.class.getName()).log(Level.SEVERE, null, ex);
        }
}

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtMobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileNoActionPerformed

    private void designationComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_designationComboMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_designationComboMouseClicked

    private void designationComboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_designationComboMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_designationComboMouseEntered

    private void designationComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designationComboActionPerformed
        // TODO add your handling code here:
  //      select();
    if(designationCombo.getSelectedIndex()>0){
        conEngrNCombo.removeAllItems();
           combo2();
       }
    
    }//GEN-LAST:event_designationComboActionPerformed
public void add(){
        String designation =designationCombo.getSelectedItem().toString();
        String conEngrN =conEngrNCombo.getSelectedItem().toString();
        String MobileNo=txtMobileNo.getText();
        String Profession=txtProfession.getText();
        String Category=txtCategory.getText();
        String Details=txtDetails.getText();
        String Amount=txtAmount.getText();
        long millis=System.currentTimeMillis();  
        java.sql.Date date=new java.sql.Date(millis);  
         if(MobileNo.isEmpty()== true ||Profession.isEmpty()==true||Category.isEmpty()==true||Details.isEmpty()==true||Amount.isEmpty()==true){
            JOptionPane.showMessageDialog(this,"Please enter all records.");
        }
         else if(designationCombo.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"Please select the designation.");             
         } 
        else{ 
            try {
        int MobileNoi=Integer.parseInt(MobileNo);      
        int Amounti=Integer.parseInt(Amount);
                pst=con.prepareStatement("INSERT INTO `con_engr_comission` (`date`,`designation`,`name`,`mobile`,`profession`,`category`,`details`,`amount`) values(?,?,?,?,?,?,?,?)");
                pst.setDate(1,date);
                pst.setString(2,designation);
                pst.setString(3,conEngrN);
                pst.setInt(4,MobileNoi);
                pst.setString(5,Profession);
                pst.setString(6,Category);
                pst.setString(7,Details);
                pst.setInt(8,Amounti);                
                pst.executeUpdate(); 
                JOptionPane.showMessageDialog(this,"Data add success !!!!!");
//                clear();
            } catch (SQLException ex) {
                Logger.getLogger(Con_eng_commission.class.getName()).log(Level.SEVERE, null, ex);
            }
        }}
public void loadWindow(){
     String sid="0";
        try {
            pst=con.prepareStatement("SELECT `id` FROM `con_engr_comission`");
            rs=pst.executeQuery();
        while(rs.next()){
         sid=rs.getString(1);
        }
        int cid=Integer.parseInt(sid);
        cid=cid+1;
        txtId.setText(cid+"");
        clear();
        } catch (SQLException ex) {
            Logger.getLogger(Con_eng_commission.class.getName()).log(Level.SEVERE, null, ex);
        }
}
public void clear(){
    txtMobileNo.setText("");
    txtProfession.setText("");
    txtCategory.setText("");
    txtDetails.setText("");
    txtAmount.setText("");
}
public void loadTable(){
        //dateBox();
        try {
         DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
               //dt.setRowCount(0);
            String sid="";
            sid=txtId.getText();
            int id=Integer.parseInt(sid);
            pst=con.prepareStatement("select *from con_engr_comission where id=?");
            pst.setInt(1,id);
            rs=pst.executeQuery();
        while(rs.next()){
         dt.addRow(new Object[]{rs.getString(2),rs.getString(3),rs.getString(4)
                                ,rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)});
        }
       clear();
        } catch (SQLException ex) {
            Logger.getLogger(Con_eng_commission.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            add();
            loadTable();
            loadWindow();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void conEngrNComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conEngrNComboMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_conEngrNComboMouseClicked

    private void conEngrNComboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conEngrNComboMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_conEngrNComboMouseEntered
public void combo2(){
    try {
            pst=con.prepareStatement("SELECT `name` FROM `contructor_engineer` WHERE `designation`=?");
            pst.setString(1,designationCombo.getSelectedItem().toString());
            rs=pst.executeQuery();
             while(rs.next()){
         conEngrNCombo.addItem(rs.getString(1));
        }            
        } catch (SQLException ex) {
            Logger.getLogger(Con_eng_commission.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    private void conEngrNComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conEngrNComboActionPerformed
     
    }//GEN-LAST:event_conEngrNComboActionPerformed

    private void txtProfessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessionActionPerformed

    private void txtCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoryActionPerformed

    private void txtDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDetailsActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new StartWindow().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Con_eng_commission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Con_eng_commission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Con_eng_commission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Con_eng_commission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Con_eng_commission().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> conEngrNCombo;
    private javax.swing.JLabel date;
    private javax.swing.JComboBox<String> designationCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtDetails;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMobileNo;
    private javax.swing.JTextField txtProfession;
    // End of variables declaration//GEN-END:variables

  
}
