/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Data_entry;

import Main.StartWindow;
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sakib
 */
public class Employe_Sales_Targets extends javax.swing.JFrame {

    /**
     * Creates new form Employe_Sales_Targets
     */
    public Employe_Sales_Targets() {
        initComponents(); 
        connect();
        loadWindow();
        comboBox();
    }
Connection con;
PreparedStatement pst=null;
ResultSet rs=null,rs2=null,rs3=null;
public void connect(){ 
        try {
            con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/chemical_company", "root", "");
        } catch (SQLException ex) {
           Logger.getLogger(Employe_Sales_Targets.class.getName()).log(Level.SEVERE, null, ex);
        }
}
public void comboBox(){
        try {
            rs=null;
            pst=con.prepareStatement("SELECT `name` FROM `employe`");
            rs=pst.executeQuery();
             while(rs.next()){
         employeeNCombo.addItem(rs.getString(1));
        }
             rs2=null;
          pst=con.prepareStatement("SELECT pName FROM product_information");
            rs2=pst.executeQuery();
             while(rs2.next()){
         productNCombo.addItem(rs2.getString(1));
        }
        } catch (SQLException ex) {
            Logger.getLogger(Employe_Sales_Targets.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        date = new javax.swing.JLabel();
        txtEmployeMobile = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        employeeNCombo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        productNCombo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtEmployeId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTargetQ = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employe Name", "Employe Id", "Employe Mobile no.", "Product name", "Target quantity"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 210, 1270, 290);
        jPanel1.add(date);
        date.setBounds(900, 10, 220, 30);

        txtEmployeMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeMobileActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmployeMobile);
        txtEmployeMobile.setBounds(420, 90, 160, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Product name :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 130, 110, 30);

        employeeNCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item" }));
        employeeNCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeNComboMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeeNComboMouseEntered(evt);
            }
        });
        employeeNCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeNComboActionPerformed(evt);
            }
        });
        jPanel1.add(employeeNCombo);
        employeeNCombo.setBounds(20, 90, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Employe Mobile no. :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(430, 60, 150, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(420, 160, 160, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Employe Name :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 60, 110, 30);

        productNCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item" }));
        productNCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productNComboMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productNComboMouseEntered(evt);
            }
        });
        productNCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNComboActionPerformed(evt);
            }
        });
        jPanel1.add(productNCombo);
        productNCombo.setBounds(20, 160, 150, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText(" Employe ID :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(240, 60, 90, 30);

        txtEmployeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmployeId);
        txtEmployeId.setBounds(200, 90, 180, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Target quantity :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(220, 130, 120, 30);

        txtTargetQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTargetQActionPerformed(evt);
            }
        });
        jPanel1.add(txtTargetQ);
        txtTargetQ.setBounds(200, 160, 180, 30);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId);
        txtId.setBounds(690, 90, 70, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Id : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(650, 90, 40, 30);

        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(1080, 80, 90, 30);

        jLabel13.setBackground(new java.awt.Color(102, 255, 102));
        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel13.setText(" *Employee sales target add : ");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 10, 330, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1330, 640);

        setSize(new java.awt.Dimension(1350, 680));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void txtEmployeMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeMobileActionPerformed

    private void employeeNComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeNComboMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeNComboMouseClicked
public void loadWindow(){
     String sid="0";
        try {
            rs2=null;
            pst=con.prepareStatement("SELECT `id` FROM `employe_sales_target`");
            rs2=pst.executeQuery();
        while(rs2.next()){
         sid=rs2.getString(1); }
        int cid=Integer.parseInt(sid);
        cid=cid+1;
        sid=Integer.toString(cid);
        txtId.setText(sid);
        clear();
        } catch (SQLException ex) {
            Logger.getLogger(Employe_Sales_Targets.class.getName()).log(Level.SEVERE, null, ex);
        }}
public void clear(){
    txtEmployeMobile.setText("");
    txtTargetQ.setText("");
    txtEmployeMobile.setText("");
    productNCombo.setSelectedIndex(0);
    
}
public void add(){
        String employeN=employeeNCombo.getSelectedItem().toString();
        String EmployeId=txtEmployeId.getText();
        String EmployeMobile=txtEmployeMobile.getText();
        String productN=productNCombo.getSelectedItem().toString();
        String TargetQ=txtTargetQ.getText(); 
         if(EmployeId.isEmpty()==true||EmployeMobile.isEmpty()==true||TargetQ.isEmpty()==true){
          JOptionPane.showMessageDialog(this,"Please enter all records.");
         }
         else if(employeeNCombo.getSelectedIndex()==0||productNCombo.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"Please select item.");             
         } 
        else{ 
            try {
        int EmployeIdi=Integer.parseInt(EmployeId);
        int EmployeMobilei=Integer.parseInt(EmployeMobile);
        int TargetQi=Integer.parseInt(TargetQ);
                pst=con.prepareStatement("INSERT INTO `employe_sales_target` (`employe_name`,`employe_id`,`employe_mobile_no`,`product_name`,`target_quantity`)VALUES(?,?,?,?,?)");
                pst.setString(1,employeN);
                pst.setInt(2,EmployeIdi);
                pst.setInt(3,EmployeMobilei);
                pst.setString(4,productN);               
                pst.setInt(5,TargetQi);               
                pst.executeUpdate(); 
                JOptionPane.showMessageDialog(this,"Data add success !!!!!");
                 loadTable();
                loadWindow();
                
            } catch (SQLException ex) {
                Logger.getLogger(Employe_Sales_Targets.class.getName()).log(Level.SEVERE, null, ex);
            }
   }}
    private void employeeNComboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeNComboMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeNComboMouseEntered

    private void employeeNComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeNComboActionPerformed
        // TODO add your handling code here:
        //      select();
            txtEmployeId.setText("");
            
    }//GEN-LAST:event_employeeNComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        add();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void productNComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productNComboMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_productNComboMouseClicked

    private void productNComboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productNComboMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_productNComboMouseEntered
public void loadTable(){
        //dateBox();
        try {
         DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
            //dt.setRowCount(0);
            String sid="";
            sid=txtId.getText();
            int id=Integer.parseInt(sid);
            rs3=null;
            pst=con.prepareStatement("select *from `employe_sales_target` where id=?");
            pst.setInt(1,id);
            rs3=pst.executeQuery();
        while(rs3.next()){
         dt.addRow(new Object[]{rs3.getString(2),rs3.getString(3),rs3.getString(4)
                                ,rs3.getString(5),rs3.getString(6)});
        }
      // clear();
        } catch (SQLException ex) {
            Logger.getLogger(Employe_Sales_Targets.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void productNComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNComboActionPerformed

    private void txtEmployeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeIdActionPerformed

    private void txtTargetQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTargetQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTargetQActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new StartWindow().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employe_Sales_Targets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employe_Sales_Targets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employe_Sales_Targets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employe_Sales_Targets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employe_Sales_Targets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JComboBox<String> employeeNCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> productNCombo;
    private javax.swing.JTextField txtEmployeId;
    private javax.swing.JTextField txtEmployeMobile;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtTargetQ;
    // End of variables declaration//GEN-END:variables
}
