/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Data_entry;
import Main.StartWindow;
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sakib
 */
public class Utility_cost extends javax.swing.JFrame {

    /**
     * Creates new form Utility_cost
     */
    public Utility_cost() {
        initComponents();
        connect();
        loadWindow();
        loadTable();
    }
Connection con;
PreparedStatement pst=null;
ResultSet rs=null,rs2=null,rs3=null,rs4=null,rs5=null,rs6=null,rs7=null,rs8=null,rs9=null,rs10=null,rs11=null;
int oldAmounts=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        date = new javax.swing.JLabel();
        txtExpenses = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        categoryCombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SL", "Date", "Expenses category", "Expenses details", "Amount"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 1230, 250);
        jPanel1.add(date);
        date.setBounds(900, 10, 220, 30);

        txtExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpensesActionPerformed(evt);
            }
        });
        jPanel1.add(txtExpenses);
        txtExpenses.setBounds(200, 90, 170, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Expenses details :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(230, 60, 130, 30);

        categoryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item", "Transport", "Labour", "Guest", "Electricity bill", "Other's" }));
        categoryCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryComboMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                categoryComboMouseEntered(evt);
            }
        });
        categoryCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboActionPerformed(evt);
            }
        });
        jPanel1.add(categoryCombo);
        categoryCombo.setBounds(20, 90, 150, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(610, 80, 130, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Amount :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(450, 60, 70, 30);

        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        jPanel1.add(txtAmount);
        txtAmount.setBounds(390, 90, 180, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Expenses category :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 60, 140, 30);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId);
        txtId.setBounds(820, 90, 70, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Id : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(840, 60, 40, 30);

        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(1140, 80, 90, 30);

        jLabel15.setBackground(new java.awt.Color(102, 255, 102));
        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel15.setText(" *Others cost :");
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 10, 160, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1260, 600);

        setSize(new java.awt.Dimension(1279, 643));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void categoryComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryComboMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryComboMouseClicked
public void connect(){ 
        try {
            con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/chemical_company", "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(Utility_cost.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    private void categoryComboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryComboMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryComboMouseEntered

    private void categoryComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboActionPerformed
        // TODO add your handling code here:
        //      select();
    }//GEN-LAST:event_categoryComboActionPerformed
public void loadWindow(){
     String sid="0";
        try {
            pst=con.prepareStatement("SELECT `id` FROM `utility_cost`");
            rs2=pst.executeQuery();
        while(rs2.next()){
         sid=rs2.getString(1);
        }
        int cid=Integer.parseInt(sid);
        cid=cid+1;
        txtId.setText(cid+"");
        } catch (SQLException ex) {
            Logger.getLogger(Utility_cost.class.getName()).log(Level.SEVERE, null, ex);
        }}
public void loadTable(){
        //dateBox();
        try {
         DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
            dt.setRowCount(0);
            String sid="";
            sid=txtId.getText();
            int id=Integer.parseInt(sid);
            pst=con.prepareStatement("select *from `utility_cost`");
            rs3=pst.executeQuery();
        while(rs3.next()){
         dt.addRow(new Object[]{rs3.getString(1),rs3.getString(2),rs3.getString(3),rs3.getString(4)
                                ,rs3.getString(5)});
        }
      // clear();
        } catch (SQLException ex) {
            Logger.getLogger(Utility_cost.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
public void add(){
        String category =categoryCombo.getSelectedItem().toString();
        String expenses=txtExpenses.getText();
        String amount=txtAmount.getText();
        long millis=System.currentTimeMillis();  
        java.sql.Date date=new java.sql.Date(millis);  
         if(expenses.isEmpty()==true||amount.isEmpty()==true){
            JOptionPane.showMessageDialog(this,"Please enter all records.");
        }
         else if(categoryCombo.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"Please select the designation.");             
         } 
        else{ 
            try {
        int Amounti=Integer.parseInt(amount);
                pst=con.prepareStatement("INSERT INTO `utility_cost` (`date`,`expenses_category`,`expenses_details`,`amount`) values(?,?,?,?)");
                pst.setDate(1,date);
                pst.setString(2,category);
                pst.setString(3,expenses);
                pst.setInt(4,Amounti);               
                pst.executeUpdate(); 
                JOptionPane.showMessageDialog(this,"Data add success !!!!!");
                 loadTable();
                loadWindow();
//                clear();
            } catch (SQLException ex) {
                Logger.getLogger(Utility_cost.class.getName()).log(Level.SEVERE, null, ex);
            }
        }}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      add();
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void txtExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpensesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpensesActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new StartWindow().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utility_cost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utility_cost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utility_cost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utility_cost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utility_cost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoryCombo;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtExpenses;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
