/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cash;

import Main.StartWindow;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author sakib
 */
public class Cash_Amount extends javax.swing.JFrame {
Connection con;
java.sql.PreparedStatement pst;
ResultSet rs,rs2,rs3;
    /**
     * Creates new form Cash_Amount
     */
    public Cash_Amount() {
        initComponents();
        connect();
        load(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtDetails = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtAmount = new javax.swing.JTextField();
        rb2 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCash = new javax.swing.JTextField();
        txtCredits = new javax.swing.JTextField();
        txtDebits = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Cash Amount");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 170, 36);

        jLabel3.setText("Amount :");

        txtDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDetailsActionPerformed(evt);
            }
        });

        jLabel1.setText("Details :");

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb2);
        rb2.setText("Debit");

        buttonGroup1.add(rb1);
        rb1.setText("Credit");

        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 391, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAmount, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDetails, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 60, 1250, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Event", "Details", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 1250, 300);

        jPanel2.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Credit : ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 10, 110, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Debit : ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 50, 110, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Today's Cash : ");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 90, 110, 30);
        jPanel2.add(txtCash);
        txtCash.setBounds(140, 90, 220, 30);
        jPanel2.add(txtCredits);
        txtCredits.setBounds(140, 10, 220, 30);

        txtDebits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDebitsActionPerformed(evt);
            }
        });
        jPanel2.add(txtDebits);
        txtDebits.setBounds(140, 50, 220, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(890, 430, 370, 140);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1270, 590);

        setSize(new java.awt.Dimension(1287, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void connect(){
        try {
            con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/chemical_company", "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(Cash_Amount.class.getName()).log(Level.SEVERE, null, ex);
        }
}
public void current_date(){
    try {
        // DateTimeFormatter tm = DateTimeFormatter.ofPattern("HH:mm:ss");
        DateTimeFormatter cdt = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        String cdate=cdt.format(now);
        
        //  String sDate=cdate;
        java.util.Date date1=new SimpleDateFormat("dd/MM/yyyy").parse(cdate);
        // String time=tm.format(now);
      //  txtDate.setDate(date1);
        txtAmount.requestFocus(true);
        // System.out.println(date.format(now));
        // System.out.println(time.format(now));
    } catch (ParseException ex) {
        Logger.getLogger(Cash_Amount.class.getName()).log(Level.SEVERE, null, ex);
    }
}
public void load(){
    current_date();
    try {
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        dt.setRowCount(0);
        pst=con.prepareStatement("select *from cash_amount");
        rs=pst.executeQuery(); 
        while(rs.next()){
            dt.addRow(new Object[]{rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});
        }
         cash();
    } catch (SQLException ex) {
        Logger.getLogger(Cash_Amount.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    private void txtDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDetailsActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed
    public void add(){
        String samount = txtAmount.getText();
        String details = txtDetails.getText();
        long millis=System.currentTimeMillis();  
        java.sql.Date date=new java.sql.Date(millis);  
        String event = null;
        if(rb1.isSelected()){
            event=rb1.getText(); }
        if(rb2.isSelected()){
            event=rb2.getText();
        }
        if(samount.isEmpty()==true ||details.isEmpty()==true ){
            JOptionPane.showMessageDialog(this,"Please enter all records.");
        }
        else if(rb1.isSelected()!=true && rb2.isSelected()!=true){
            JOptionPane.showMessageDialog(this,"Select event"); 
        }
        else{
            try {
                pst=con.prepareStatement("insert into cash_amount(date,event,details,amount) values(?,?,?,?)");
                pst.setDate(1,date);
                pst.setString(2, event);
                pst.setString(3,details);
                int amount=Integer.parseInt(samount);
                pst.setInt(4, amount);
                pst.executeUpdate(); 
                JOptionPane.showMessageDialog(this,"Data add success !!!!!");
                txtAmount.setText("");
                txtDetails.setText("");
                txtAmount.setText("");
                rb1.setSelected(false);
                rb2.setSelected(false);
            } catch (SQLException ex) {
                Logger.getLogger(Cash_Amount.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        }
        // Date ddate=new SimpleDateFormat("yyyy/MM/dd").parse(sDate);
        
    }
    public void cash(){
    try {
        pst=con.prepareStatement("SELECT SUM(`Amount`)FROM `cash_amount` WHERE `Event`='Credit'");
        rs=pst.executeQuery(); 
        pst=con.prepareStatement("SELECT SUM(`Amount`)FROM `cash_amount` WHERE `Event`='Debit'");
        rs2=pst.executeQuery(); 
        while(rs.next() && rs2.next()){
            String cre =Integer.toString(rs.getInt(1));
            String deb =Integer.toString(rs2.getInt(1));
            int c=rs.getInt(1)-rs2.getInt(1);
            String cash=Integer.toString(c);
            txtCredits.setText(cre);
            txtDebits.setText(deb);
            txtCash.setText(cash);
            
        }
    } catch (SQLException ex) {
        Logger.getLogger(Cash_Amount.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // submit
        add();
        load();
        cash();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtDebitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDebitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDebitsActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new StartWindow().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cash_Amount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cash_Amount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cash_Amount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cash_Amount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cash_Amount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtCredits;
    private javax.swing.JTextField txtDebits;
    private javax.swing.JTextField txtDetails;
    // End of variables declaration//GEN-END:variables
}
