/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Information_add;

import Main.StartWindow;
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sakib
 */
public class Product_information extends javax.swing.JFrame {
Connection con;
PreparedStatement pst=null;
ResultSet rs=null;
    public Product_information() {
        initComponents();
        connect();
        load();
    }
public void connect(){ 
            try {
                con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/chemical_company", "root", "");
            } catch (SQLException ex) {
                Logger.getLogger(Product_information.class.getName()).log(Level.SEVERE, null, ex);
            }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        date = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtsellsPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtpurchasePrice = new javax.swing.JTextField();
        txtpName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Product Name", "Purchase Price", "Sells Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(450, 100, 780, 400);
        jPanel1.add(date);
        date.setBounds(900, 10, 220, 30);

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(230, 220, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Sells price : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 160, 100, 30);

        txtsellsPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsellsPriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtsellsPrice);
        txtsellsPrice.setBounds(120, 160, 220, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Purchase price :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 110, 110, 30);

        txtpurchasePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpurchasePriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtpurchasePrice);
        txtpurchasePrice.setBounds(120, 110, 220, 30);

        txtpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtpName);
        txtpName.setBounds(120, 70, 220, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Product Name :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 60, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Id : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 220, 40, 30);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId);
        txtId.setBounds(120, 220, 80, 30);

        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(1150, 50, 70, 30);

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtn);
        clearBtn.setBounds(370, 60, 80, 30);

        jLabel10.setBackground(new java.awt.Color(102, 255, 102));
        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel10.setText(" *Product Information :");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 10, 270, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1240, 520);

        setSize(new java.awt.Dimension(1256, 559));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void load(){
        String sid="0";
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        dt.setRowCount(0);
        try {
            pst=con.prepareStatement("select *from product_information");
            rs=pst.executeQuery();
        while(rs.next()){
         dt.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)});
         sid=rs.getString(1);
        }
        int cid=Integer.parseInt(sid);
        cid=cid+1;
        sid=Integer.toString(cid);
        txtId.setText(sid);
          clear();
         txtpName.requestFocus();
        } catch (SQLException ex) {
            Logger.getLogger(Employe_Information.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void txtpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpNameActionPerformed

    private void txtpurchasePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpurchasePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpurchasePriceActionPerformed
public void clear(){
     txtpName.setText("");
     txtpurchasePrice.setText("");
     txtsellsPrice.setText("");
   
}
    private void txtsellsPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsellsPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsellsPriceActionPerformed
public void add(){
        String name=txtpName.getText();
        String spurchasePrice=txtpurchasePrice.getText();
        String ssellsPrice=txtsellsPrice.getText();
        long millis=System.currentTimeMillis();  
        java.sql.Date date2=new java.sql.Date(millis);  
         if(name.isEmpty()== true ||spurchasePrice.isEmpty()==true||ssellsPrice.isEmpty()==true){
            JOptionPane.showMessageDialog(this,"Please enter all records.");
        }
        else{ 
            try {
                pst=con.prepareStatement("insert into product_information (pname,purchasePrice,sellsPrice) values(?,?,?)");
                pst.setString(1,name);
                pst.setString(2,spurchasePrice);
                pst.setString(3,ssellsPrice);
                pst.executeUpdate(); 
                JOptionPane.showMessageDialog(this,"Data add success !!!!!");
                clear();
              
            } catch (SQLException ex) {
                Logger.getLogger(Employe_Information.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        }}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        add();
      load();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //selected
        DefaultTableModel dt = (DefaultTableModel)jTable1.getModel();
        String tbId = dt.getValueAt(jTable1.getSelectedRow(),0).toString();
        String tbpName = dt.getValueAt(jTable1.getSelectedRow(),1).toString();
        String tbpurchasePrice = dt.getValueAt(jTable1.getSelectedRow(),2).toString();
        String tbsellsPrice = dt.getValueAt(jTable1.getSelectedRow(),3).toString();
        txtId.setText(tbId);
        txtpName.setText(tbpName);   
        txtpurchasePrice.setText(tbpurchasePrice);
        txtsellsPrice.setText(tbsellsPrice);
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new StartWindow().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        load();
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product_information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtpName;
    private javax.swing.JTextField txtpurchasePrice;
    private javax.swing.JTextField txtsellsPrice;
    // End of variables declaration//GEN-END:variables
}
