/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Information_add;

import Main.StartWindow;
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sakib
 */
public class Supplier_information extends javax.swing.JFrame {
Connection con;
PreparedStatement pst=null;
ResultSet rs=null;
    /**
     * Creates new form Supplier_information
     */
    public Supplier_information() {
        initComponents();
        connect();
        load();
    }
    public void dateBox(){
        DateTimeFormatter cdt = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        String cdate=cdt.format(now);
        dateBox.setText(cdate);
                
    }
public void connect(){ 
            try {
                con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/chemical_company", "root", "");
            } catch (SQLException ex) {
                Logger.getLogger(Supplier_information.class.getName()).log(Level.SEVERE, null, ex);
            }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        dateBox = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        txtCName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDetails = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Company Name", "Address", "Phone number", "Details", "Date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 1110, 270);

        dateBox.setBackground(new java.awt.Color(51, 255, 51));
        dateBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dateBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(dateBox);
        dateBox.setBounds(490, 20, 220, 30);

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(810, 100, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Id : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(770, 60, 40, 30);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId);
        txtId.setBounds(810, 60, 100, 30);

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(720, 430, 110, 30);

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(360, 430, 110, 30);

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(480, 430, 110, 30);

        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(600, 430, 110, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Phone number :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(380, 60, 110, 30);

        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });
        jPanel1.add(txtPhoneNumber);
        txtPhoneNumber.setBounds(490, 60, 220, 30);

        txtCName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtCName);
        txtCName.setBounds(130, 60, 230, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Company Name :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 60, 120, 30);

        txtDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDetailsActionPerformed(evt);
            }
        });
        jPanel1.add(txtDetails);
        txtDetails.setBounds(490, 100, 220, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Details :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 100, 110, 30);

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtAddress);
        txtAddress.setBounds(130, 100, 230, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Address :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 100, 120, 30);

        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(1030, 100, 90, 30);

        jLabel10.setBackground(new java.awt.Color(102, 255, 102));
        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel10.setText(" *Supplier Information :");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 10, 270, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1130, 600);

        setSize(new java.awt.Dimension(1146, 641));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void load(){
        dateBox();
        String sid="0";
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        dt.setRowCount(0);
        try {
            pst=con.prepareStatement("select *from supplier_information");
            rs=pst.executeQuery();
        while(rs.next()){
         dt.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)
                                ,rs.getString(5),rs.getString(6)});
         sid=rs.getString(1);
        }
        int cid=Integer.parseInt(sid);
        cid=cid+1;
        sid=Integer.toString(cid);
        txtId.setText(sid);
        //  clear();
         txtCName.requestFocus();
         clear();
        } catch (SQLException ex) {
            Logger.getLogger(Supplier_information.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDetailsActionPerformed


    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //selected
        DefaultTableModel dt = (DefaultTableModel)jTable1.getModel();
        String tbid = dt.getValueAt(jTable1.getSelectedRow(),0).toString();
        String tbcname = dt.getValueAt(jTable1.getSelectedRow(),1).toString();
        String tbaddress = dt.getValueAt(jTable1.getSelectedRow(),2).toString();
        String tbphone = dt.getValueAt(jTable1.getSelectedRow(),3).toString();
        String details= dt.getValueAt(jTable1.getSelectedRow(),4).toString();
        String date= dt.getValueAt(jTable1.getSelectedRow(),5).toString();
        txtId.setText(tbid);
        txtCName.setText(tbcname);
        txtAddress.setText(tbaddress);                            // Item Contructor Engineer Others
        txtPhoneNumber.setText(tbphone);
        txtDetails.setText(details);
        dateBox.setText(date);

    }//GEN-LAST:event_jTable1MouseClicked
public void add(){
        String cname=txtCName.getText();
        String phone=txtPhoneNumber.getText();
        String address=txtAddress.getText();
        String details=txtDetails.getText();
        long millis=System.currentTimeMillis();  
        java.sql.Date date=new java.sql.Date(millis);  
         if(cname.isEmpty()== true ||phone.isEmpty()==true||address.isEmpty()==true||details.isEmpty()==true){
            JOptionPane.showMessageDialog(this,"Please enter all records.");
        }
        else{ 
            try {
                pst=con.prepareStatement("insert into supplier_information (company_name,address,phone_number,details,date) values(?,?,?,?,?)");
                pst.setString(1,cname);
                pst.setString(2,address);
                pst.setString(3,phone);
                pst.setString(4,details);
                pst.setDate(5,date);
                pst.executeUpdate(); 
                JOptionPane.showMessageDialog(this,"Data add success !!!!!");
                clear();
              
            } catch (SQLException ex) {
                Logger.getLogger(Supplier_information.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        }}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        add();
        load();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // show
            String id=txtId.getText();
            int i=Integer.parseInt(id);
            pst=con.prepareStatement("select *from employe where id=?");
            pst.setInt(1,i);
            rs=pst.executeQuery();
            while(rs.next()){
                txtCName.setText(rs.getString(2));
                txtAddress.setText(rs.getString(3));
                txtPhoneNumber.setText(rs.getString(4));
                txtDetails.setText(rs.getString(5));
                dateBox.setText(rs.getString(6));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Supplier_information.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
public void update(){
        String id=txtId.getText();
         int i=Integer.parseInt(id);
       String cname=txtCName.getText();
        String address=txtAddress.getText();
        String sphoneNumber=txtPhoneNumber.getText();
        String details=txtDetails.getText();
        long millis=System.currentTimeMillis();  
        java.sql.Date date2=new java.sql.Date(millis);  
         if(cname.isEmpty()== true || address.isEmpty()==true||sphoneNumber.isEmpty()==true||details.isEmpty()==true){
            JOptionPane.showMessageDialog(this,"Please enter all records.");
        }
        else{
         try {
             pst=con.prepareStatement("update supplier_information set company_name=?,address=?,phone_number=?,details=?,date=? where id=?");
            // pst.setInt(5,i);
             pst.setString(1,cname);
             pst.setString(2, address);
             int phoneNumber=Integer.parseInt(sphoneNumber);
             pst.setInt(3,phoneNumber);
             pst.setString(4,details);
             pst.setDate(5,date2);
             pst.setInt(6,i);
             pst.executeUpdate();
             JOptionPane.showMessageDialog(this,"Data update success !!!!!");
             clear();
             load();
             txtCName.requestFocus();
         } catch (SQLException ex) {
             Logger.getLogger(Supplier_information.class.getName()).log(Level.SEVERE, null, ex);
         }
}}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // update
        update();
        load();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // delete
            String id=txtId.getText();
            int i=Integer.parseInt(id);
            pst=con.prepareStatement("delete from supplier_information where id=?");
            pst.setInt(1,i);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Data delete success !!!!!");
            load();
            txtCName.requestFocus();
        } catch (SQLException ex) {
            Logger.getLogger(Supplier_information.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed
 public void clear(){
         txtCName.setText("");
         txtAddress.setText("");
         txtPhoneNumber.setText("");
         txtDetails.setText("");
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        load();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtCNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNameActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new StartWindow().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier_information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCName;
    private javax.swing.JTextField txtDetails;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
